### ISSUE TITLE
Controller Bikes

### ISSUE THREAD

**Issue by egalli64** [egalli64/joBikes185#4]
Bikes on the controller

**Comment by egalli64** [comment]
See ticket #6

Bike*

**Comment by SigniferRuber** [comment]
Committed the 3 java files (entity, repo, ctrl) for the base version.
Once all is working fine, the "select bike by station" function will be implemented.
FL

**Comment by egalli64** [comment]
/bikes/saves should accept calls with no user id also

**Comment by SigniferRuber** [comment]
/bikes/saves should accept calls with no user id also - done
